substitutions:
  _AR_REPO: team-53        # check Artifact Registry name
  _IMAGE_NAME: team-53-api      # your container name
  _SERVICE_NAME: team-53-api    # your Cloud Run service name
  _REGION: us-central1          # Cloud Run region
  _RUNTIME_SA: team-53-run-sa@team-53-str.iam.gserviceaccount.com

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "fetch-data"
    entrypoint: bash
    args:
      - -c
      - |
        echo "📦 Downloading data and Pops model files from GCS..."

        mkdir -p data
        mkdir -p app/models

        # Download cleaned data file
        gsutil -m cp gs://team-53-data/data/df_clean_city_subset_111725.csv data/

        # Download pops_ model folder into app/models/
        gsutil -m cp -r gs://team-53-data/models/pops_ app/models/

        echo "✅ Finished fetching data from GCS."



  # Step 2: Build Docker image (includes data + models)
  - name: 'gcr.io/cloud-builders/docker'
    id: "build-image"
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    id: "verify-image"
    args:
      - 'run'
      - '--rm'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME'
      - 'sh'
      - '-c'
      - 'ldconfig -p | grep libgomp || echo "❌ libgomp NOT FOUND"'
  
  # Step 3: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: "push-image"
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME'
    ]

  # Step 3: Deploy to Cloud Run using runtime service account
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: "deploy-run"
    entrypoint: gcloud 
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NAME',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME',
        '--region',
        '$_REGION',
        '--allow-unauthenticated',
        '--service-account',
        '$_RUNTIME_SA',
        '--memory',
        '4Gi', 
        '--cpu',
        '1',
        '--update-secrets',
        'OPENAI_API_KEY=openai-api-key:latest'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME'

options:
  logging: CLOUD_LOGGING_ONLY