substitutions:
  _AR_REPO: team-53        # check Artifact Registry name
  _IMAGE_NAME: team-53-api      # your container name
  _SERVICE_NAME: team-53-api    # your Cloud Run service name
  _REGION: us-central1          # Cloud Run region
  _RUNTIME_SA: team-53-run-sa@team-53-str.iam.gserviceaccount.com

steps:
  # Step 0: Download data & models from GCS into /workspace before build
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "fetch-data"
    entrypoint: bash
    args:
      - -c
      - |
        echo "📦 Downloading geo and model files from GCS..."
        mkdir -p data/geo models
        gsutil -m cp gs://team-53-data/geo/zcta_3857.parquet data/geo/
        gsutil -m cp gs://team-53-data/models/pipeline.joblib models/
        gsutil -m cp gs://team-53-data/models/infer_meta.json models/
        echo "✅ Finished fetching data from GCS."

  # Step 1: Run quick tests (non-blocking)
  - name: 'python:3.12'
    id: "run-tests"
    entrypoint: bash
    args:
      - -c
      - |
        echo "🧪 Running tests..."
        pip install -r requirements.txt >/dev/null 2>&1 || true
        pytest -q || echo "⚠️  Skipping tests (non-blocking)."
        echo "✅ Test step complete."

  # Step 2: Build Docker image (includes data + models)
  - name: 'gcr.io/cloud-builders/docker'
    id: "build-image"
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME',
        '.'
      ]

  # Step 3: Deploy to Cloud Run using runtime service account
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: "deploy-run"
    entrypoint: gcloud 
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NAME',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME',
        '--region',
        '$_REGION',
        '--allow-unauthenticated',
        '--service-account',
        '$_RUNTIME_SA'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME'

options:
  logging: CLOUD_LOGGING_ONLY