# embedding features
PERF_FEATS = [
    "estimated_occupancy_l365d",
    "estimated_revenue_l365d",
    "price_capped",
    "availability_30",
    "availability_60",
    "availability_90",
    "reviews_per_month",
    "number_of_reviews_ltm",
    "review_scores_rating",
    "number_of_reviews",
    "number_of_reviews_l30d",
    "number_of_reviews_ltm",
    "number_of_reviews_ly",
    "days_as_host",
    "days_since_first_review",
    "days_since_last_review",
]

# unclear if we need these
CONTROL_FEATS = [
    "accommodates",
    "air_conditioning",
    "bathrooms",
    "bedrooms",
    "beds",
    "free_parking",
    "gym",
    "heating",
    "hot_tub",
    "hot_tub_private",
    "hot_tub_shared",
    "housekeeping",
    "paid_parking",
    "pool",
    "pool_indoor",
    "pool_outdoor",
    "pool_private",
    "pool_shared",
    "privacy_private",
    "privacy_room in",
    "privacy_shared",
    "room_type_Hotel room",
    "room_type_Private room",
    "room_type_Shared room",
]

# for KNN inference setup
STRUCTURAL_FEATS = [
    "hot_tub",
    "percent_work_from_home",
    "dist_to_bus_km",
    "race_other",
    "air_conditioning",
    "dist_to_park_km",
    "housekeeping",
    "pool_shared",
    "paid_parking",
    "avg_price",
    "latitude",
    "median_home_value",
    "race_asian",
    "hot_tub_shared",
    "unemployed",
    "percent_public_transport",
    "pool_outdoor",
    "pool_indoor",
    "gini_index",
    "med_price",
    "hot_tub_private",
    "percent_foreign_born",
    "heating",
    "race_black",
    "labor_force",
    "beds",
    "pool_private",
    "dist_to_train_km",
    "percent_owner_occupied",
    "unemployment_rate",
    "accommodates",
    "bathrooms",
    "median_year_built",
    "dist_to_airport_km",
    "commute_time_mean",
    "percent_over_65",
    "gym",
    "education_bachelors",
    "free_parking",
    "vacancy_rate",
    "median_gross_rent",
    "dist_to_university_km",
    "median_income",
    "dist_to_city_center_km",
    "poverty_rate",
    "bedrooms",
    "race_white",
    "median_age",
    "pool",
    "total_housing_units",
    "longitude",
    "population",
    "room_type_Hotel room",
    "room_type_Private room",
    "room_type_Shared room",
    "privacy_private",
    "privacy_room in",
    "privacy_shared",
]
